import { Geist, Geist_Mono, DM_Sans as DMSansFont } from "next/font/google";

import "./globals.css";
import Navbar from "@/components/navbar";
import { AuthProvider } from "@/contexts/AuthContext";
import ConditionalProtectedRoute from "@/components/ConditionalProtectedRoute";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const dmSans = DMSansFont({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}  ${dmSans.variable} antialiased`}
      >
        <AuthProvider>
          <ConditionalProtectedRoute>{children}</ConditionalProtectedRoute>
        </AuthProvider>
      </body>
    </html>
  );
}
