/**
 * Sample Data for Employee Retention Testing
 * This file contains mock data for testing the retention prediction module
 */

export const sampleEmployees = [
  {
    id: 1,
    name: "John Doe",
    department: "Engineering",
    position: "Senior Software Engineer",
    jobSatisfaction: 7,
    engagementLevel: 8,
    tenure: 3.5,
    workLifeBalance: 6,
    salarySatisfaction: 7,
    careerGrowth: 6,
    managerRelationship: 8,
    performanceScore: 8,
    email: "john.doe@company.com",
  },
  {
    id: 2,
    name: "Jane Smith",
    department: "Marketing",
    position: "Marketing Manager",
    jobSatisfaction: 4,
    engagementLevel: 5,
    tenure: 1.2,
    workLifeBalance: 4,
    salarySatisfaction: 5,
    careerGrowth: 3,
    managerRelationship: 6,
    performanceScore: 7,
    email: "jane.smith@company.com",
  },
  {
    id: 3,
    name: "Mike Johnson",
    department: "Sales",
    position: "Sales Representative",
    jobSatisfaction: 9,
    engagementLevel: 9,
    tenure: 2.8,
    workLifeBalance: 8,
    salarySatisfaction: 8,
    careerGrowth: 7,
    managerRelationship: 9,
    performanceScore: 9,
    email: "mike.johnson@company.com",
  },
  {
    id: 4,
    name: "Sarah Wilson",
    department: "HR",
    position: "HR Specialist",
    jobSatisfaction: 3,
    engagementLevel: 4,
    tenure: 0.8,
    workLifeBalance: 3,
    salarySatisfaction: 4,
    careerGrowth: 2,
    managerRelationship: 5,
    performanceScore: 6,
    email: "sarah.wilson@company.com",
  },
  {
    id: 5,
    name: "David Brown",
    department: "Finance",
    position: "Financial Analyst",
    jobSatisfaction: 6,
    engagementLevel: 6,
    tenure: 4.2,
    workLifeBalance: 7,
    salarySatisfaction: 6,
    careerGrowth: 5,
    managerRelationship: 7,
    performanceScore: 7,
    email: "david.brown@company.com",
  },
  {
    id: 6,
    name: "Lisa Garcia",
    department: "Engineering",
    position: "Frontend Developer",
    jobSatisfaction: 8,
    engagementLevel: 7,
    tenure: 2.1,
    workLifeBalance: 8,
    salarySatisfaction: 7,
    careerGrowth: 6,
    managerRelationship: 8,
    performanceScore: 8,
    email: "lisa.garcia@company.com",
  },
  {
    id: 7,
    name: "Robert Chen",
    department: "Sales",
    position: "Sales Manager",
    jobSatisfaction: 5,
    engagementLevel: 6,
    tenure: 5.5,
    workLifeBalance: 5,
    salarySatisfaction: 6,
    careerGrowth: 4,
    managerRelationship: 7,
    performanceScore: 7,
    email: "robert.chen@company.com",
  },
  {
    id: 8,
    name: "Emily Rodriguez",
    department: "Marketing",
    position: "Content Specialist",
    jobSatisfaction: 6,
    engagementLevel: 7,
    tenure: 1.8,
    workLifeBalance: 6,
    salarySatisfaction: 5,
    careerGrowth: 5,
    managerRelationship: 6,
    performanceScore: 7,
    email: "emily.rodriguez@company.com",
  },
  {
    id: 9,
    name: "Alex Thompson",
    department: "Engineering",
    position: "DevOps Engineer",
    jobSatisfaction: 2,
    engagementLevel: 3,
    tenure: 0.5,
    workLifeBalance: 2,
    salarySatisfaction: 3,
    careerGrowth: 2,
    managerRelationship: 4,
    performanceScore: 5,
    email: "alex.thompson@company.com",
  },
  {
    id: 10,
    name: "Maria Lopez",
    department: "Finance",
    position: "Senior Accountant",
    jobSatisfaction: 7,
    engagementLevel: 7,
    tenure: 6.2,
    workLifeBalance: 7,
    salarySatisfaction: 7,
    careerGrowth: 6,
    managerRelationship: 8,
    performanceScore: 8,
    email: "maria.lopez@company.com",
  },
];

export const sampleRetentionData = {
  retentionTrends: {
    current: 85.5,
    previousMonth: 87.2,
    previousQuarter: 88.1,
    yearToDate: 86.8,
    trend: "declining",
  },

  departmentAnalytics: [
    {
      department: "Engineering",
      totalEmployees: 45,
      highRisk: 3,
      mediumRisk: 8,
      lowRisk: 34,
      retentionRate: 91.2,
      avgSatisfaction: 7.8,
    },
    {
      department: "Sales",
      totalEmployees: 32,
      highRisk: 6,
      mediumRisk: 12,
      lowRisk: 14,
      retentionRate: 78.5,
      avgSatisfaction: 6.2,
    },
    {
      department: "Marketing",
      totalEmployees: 28,
      highRisk: 4,
      mediumRisk: 9,
      lowRisk: 15,
      retentionRate: 82.1,
      avgSatisfaction: 6.8,
    },
    {
      department: "HR",
      totalEmployees: 12,
      highRisk: 2,
      mediumRisk: 3,
      lowRisk: 7,
      retentionRate: 79.3,
      avgSatisfaction: 6.5,
    },
    {
      department: "Finance",
      totalEmployees: 18,
      highRisk: 1,
      mediumRisk: 4,
      lowRisk: 13,
      retentionRate: 88.9,
      avgSatisfaction: 7.4,
    },
  ],

  riskFactors: {
    primaryFactors: [
      { factor: "Job Satisfaction", impact: 28.5, trend: "declining" },
      { factor: "Career Growth", impact: 24.3, trend: "stable" },
      { factor: "Salary Satisfaction", impact: 18.7, trend: "improving" },
      { factor: "Work-Life Balance", impact: 15.2, trend: "declining" },
      { factor: "Manager Relationship", impact: 13.3, trend: "stable" },
    ],
  },

  monthlyTrends: [
    { month: "Jul 2024", retentionRate: 85.2, turnoverCount: 8 },
    { month: "Aug 2024", retentionRate: 86.9, turnoverCount: 6 },
    { month: "Sep 2024", retentionRate: 84.7, turnoverCount: 9 },
    { month: "Oct 2024", retentionRate: 85.8, turnoverCount: 7 },
    { month: "Nov 2024", retentionRate: 87.2, turnoverCount: 5 },
    { month: "Dec 2024", retentionRate: 85.5, turnoverCount: 8 },
  ],
};

export const sampleRecommendations = [
  {
    priority: "High",
    action: "Conduct stay interviews with high-risk employees",
    department: "Sales",
    expectedImpact: "Reduce turnover risk by 15-20%",
    timeline: "2 weeks",
    category: "Immediate",
    description:
      "Schedule one-on-one meetings with employees showing high risk scores to understand their concerns and develop retention strategies.",
    steps: [
      "Identify high-risk employees using AI predictions",
      "Schedule confidential stay interviews",
      "Document concerns and improvement suggestions",
      "Develop individualized retention plans",
      "Follow up monthly on progress",
    ],
  },
  {
    priority: "High",
    action: "Review and improve career development programs",
    department: "All",
    expectedImpact: "Improve career growth satisfaction by 25%",
    timeline: "1 month",
    category: "Strategic",
    description:
      "Enhance career development opportunities as this is identified as a major risk factor.",
    steps: [
      "Audit current career development programs",
      "Survey employees on career growth needs",
      "Design enhanced mentorship programs",
      "Create clear career progression paths",
      "Implement skills development initiatives",
    ],
  },
  {
    priority: "Medium",
    action: "Implement flexible work arrangements",
    department: "Marketing, HR",
    expectedImpact: "Improve work-life balance scores by 20%",
    timeline: "6 weeks",
    category: "Operational",
    description:
      "Address work-life balance concerns through flexible working options.",
    steps: [
      "Assess current work arrangement policies",
      "Design flexible work policy framework",
      "Pilot program with select departments",
      "Gather feedback and iterate",
      "Roll out company-wide",
    ],
  },
];
